version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3333:3000"  # Adjust port mappings as needed
    depends_on:
      - backend
